spring:
  profiles:
    include:
      database

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect


logging:
  level:
    org.hibernate.SQL: debug

const:
  user-loginid-length : 50
  user-password-length : 255
  user_nickname_length : 30
  board-title-length : 30
  board-content-length : 300
  comment-content-length : 200


